STAGE: ${file(serverless.yml):provider.stage}

# DynamoDB
CUSTOMERS_DYNAMODB_TABLE_ARN: !GetAtt CustomersTable.Arn
NOTIFICATION_DYNAMODB_TABLE_ARN: !GetAtt NotificationsTable.Arn

# SQS
CUSTOMERS_NOTIFICATIONS_ARN: !GetAtt customersNotificationsQueue.Arn
CUSTOMERS_NOTIFICATIONS_DLQ_ARN: !GetAtt customersNotificationsDLQ.Arn