# Customers

addCustomer:
  handler: src/api/handlers/customer/add_customer.handler
  memorySize: 256
  timeout: 20
  maximumRetryAttempts: 0
  events:
    - http:
        path: customers
        method: post
        cors: true

deleteCustomerById:
  handler: src/api/handlers/customer/delete_customer.handler
  memorySize: 256
  timeout: 20
  maximumRetryAttempts: 0
  events:
    - http:
        path: customers/{id}
        method: delete

findAllCustomers:
  handler: src/api/handlers/customer/find_all_customer.handler
  memorySize: 256
  timeout: 20
  maximumRetryAttempts: 0
  events:
    - http:
        path: customers
        method: get

findCustomerByCPF:
  handler: src/api/handlers/customer/find_customer_by_cpf.handler
  memorySize: 256
  timeout: 20
  maximumRetryAttempts: 0
  events:
    - http:
        path: customers/cpf/{cpf}
        method: get

findCustomerById:
  handler: src/api/handlers/customer/add_customer_by_id.handler
  memorySize: 256
  timeout: 20
  maximumRetryAttempts: 0
  events:
    - http:
        path: customers/{id}
        method: get

updateCustomerById:
  handler: src/api/handlers/customer/update_customer.handler
  memorySize: 256
  timeout: 20
  maximumRetryAttempts: 0
  events:
    - http:
        path: customers/{id}
        method: put


# Notifications

addNotification:
  handler: src/api/handlers/notification/add_notification.handler
  memorySize: 256
  timeout: 20
  maximumRetryAttempts: 0
  events:
    - sqs:
        arn: ${file(serverless.yml):provider.environment.CUSTOMERS_NOTIFICATIONS_ARN}
        batchSize: 1
        enabled: true


findAllNotificationsByCustomer:
  handler: src/api/handlers/notification/find_all_notifications_by_customer.handler
  memorySize: 256
  timeout: 20
  maximumRetryAttempts: 0
  events:
    - http:
        path: notifications/customer/{id}
        method: get